### ISSUE TITLE
Server should be able to pick the reduction from a list

### ISSUE THREAD

**Issue by xballoy** [kumojin/extreme-carpaccio#3]
Currently in the configuration file we can put only one type of reduction at the time (see [reduction configuration](https://github.com/kumojin/extreme-carpaccio/blob/main/server/configuration.json#L4)). We should be able to use an array of reductions.

# Definition of done

- Replace the "reduction" field by an array in the configuration file
- If the picked reduction is not known we fallback to "STANDARD" (current behaviour) to prevent crash from typo in the config file.
- Add tests 

## To be discussed

- Do we randomly pick a reduction or we can weight them?

**Comment by annemano** [comment]
I'll do this one!

And then adding weight could be done in a separate PR.
